#SPDX-License-Identifier: MIT-0
---
# tasks file for docker

- block:
  - name: add GPG key for docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  
  - name: add repository for docker
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
      state: present

  - name: update cache
    apt:
      update_cache: yes

  - name: install docker
    apt:
      name: docker-ce 
      state: present

  - name: check docker service 
    service:
      name: docker
      state: started
      enabled: yes 

  - name: add user to docker group 
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: install docker-compose
    get_url:
        url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

  - name: change file ownership, group and permissions
    ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

  become: yes
