#SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: set timezone to Europe/Moscow
  community.general.timezone:
     name: "{{ region }}/{{ city }}"

- block:
   - name: create a swap file
     shell: fallocate -l {{ swap_size }} /swapfile
     args:
      creates: /swapfile
   
   - name: set the correct permissions 
     file:
       path: /swapfile
       owner: root
       group: root
       mode: '0600'
   
   - name: make the file a swap file
     shell: mkswap /swapfile
     when: ansible_facts.swapfree_mb == 0

   - name: enable the swap file
     shell: swapon /swapfile
     when: ansible_facts.swapfree_mb == 0

   - name: add swap file to fstab
     mount:
       name: none
       src: /swapfile
       fstype: swap
       opts: sw
       passno: 0
       dump: 0
       state: present

- name: set hostname
  ansible.builtin.hostname:
      name: "{{ hostname }}"
  become: yes    
#     name: "{{ inventory_hostname }}"  

- name: update apt cache
  apt:
    update_cache: yes
  become: yes

- name: installation packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ packages }}"
  become: yes 
